### 1. Import Libraries

In [1]:
!pip install xgboost

Requirement already satisfied: xgboost in /opt/conda/lib/python3.12/site-packages (2.1.4)
Requirement already satisfied: numpy in /opt/conda/lib/python3.12/site-packages (from xgboost) (1.26.4)
Requirement already satisfied: scipy in /opt/conda/lib/python3.12/site-packages (from xgboost) (1.16.3)

In [2]:
!pip install feature-engine

Collecting feature-engine
  Using cached feature_engine-1.9.4-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: numpy>=1.18.2 in /opt/conda/lib/python3.12/site-packages (from feature-engine) (1.26.4)
Requirement already satisfied: pandas>=2.2.0 in /opt/conda/lib/python3.12/site-packages (from feature-engine) (2.3.3)
Requirement already satisfied: scikit-learn>=1.4.0 in /opt/conda/lib/python3.12/site-packages (from feature-engine) (1.7.2)
Requirement already satisfied: scipy>=1.4.1 in /opt/conda/lib/python3.12/site-packages (from feature-engine) (1.16.3)
Requirement already satisfied: statsmodels>=0.11.1 in /opt/conda/lib/python3.12/site-packages (from feature-engine) (0.14.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.12/site-packages (from pandas>=2.2.0->feature-engine) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.12/site-packages (from pandas>=2.2.0->feature-engine) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.12/site-packages (from pandas>=2.2.0->feature-engine) (2026.2)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=2.2.0->feature-engine) (1.17.0)
Requirement already satisfied: joblib>=1.2.0 in /opt/conda/lib/python3.12/site-packages (from scikit-learn>=1.4.0->feature-engine) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /opt/conda/lib/python3.12/site-packages (from scikit-learn>=1.4.0->feature-engine) (3.6.0)
Requirement already satisfied: patsy>=0.5.6 in /opt/conda/lib/python3.12/site-packages (from statsmodels>=0.11.1->feature-engine) (1.0.2)
Requirement already satisfied: packaging>=21.3 in /opt/conda/lib/python3.12/site-packages (from statsmodels>=0.11.1->feature-engine) (25.0)
Using cached feature_engine-1.9.4-py3-none-any.whl (243 kB)
Installing collected packages: feature-engine
Successfully installed feature-engine-1.9.4

In [5]:
!pip show sagemaker

Name: sagemaker
Version: 3.14.0
Summary: Open source library for training and deploying models on Amazon SageMaker.
Home-page: https://github.com/aws/sagemaker-python-sdk
Author: Amazon Web Services
Author-email:
License:
Location: /opt/conda/lib/python3.12/site-packages
Requires: sagemaker-core, sagemaker-mlops, sagemaker-serve, sagemaker-train
Required-by:

In [7]:
!pip install "sagemaker<3"

Collecting sagemaker<3
  Downloading sagemaker-2.257.3-py3-none-any.whl.metadata (17 kB)
Collecting attrs<26,>=24 (from sagemaker<3)
  Downloading attrs-25.4.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: boto3<2.0,>=1.42.2 in /opt/conda/lib/python3.12/site-packages (from sagemaker<3) (1.42.97)
Requirement already satisfied: cloudpickle>=2.2.1 in /opt/conda/lib/python3.12/site-packages (from sagemaker<3) (3.1.2)
Requirement already satisfied: docker in /opt/conda/lib/python3.12/site-packages (from sagemaker<3) (7.1.0)
Requirement already satisfied: fastapi in /opt/conda/lib/python3.12/site-packages (from sagemaker<3) (0.136.1)
Requirement already satisfied: google-pasta in /opt/conda/lib/python3.12/site-packages (from sagemaker<3) (0.2.0)
Requirement already satisfied: graphene<4,>=3 in /opt/conda/lib/python3.12/site-packages (from sagemaker<3) (3.4.3)
Requirement already satisfied: importlib-metadata<7.0,>=1.4.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker<3) (6.10.0)
Requirement already satisfied: jsonschema in /opt/conda/lib/python3.12/site-packages (from sagemaker<3) (4.23.0)
Requirement already satisfied: numpy<3.0,>=1.26.4 in /opt/conda/lib/python3.12/site-packages (from sagemaker<3) (1.26.4)
Requirement already satisfied: omegaconf<3,>=2.2 in /opt/conda/lib/python3.12/site-packages (from sagemaker<3) (2.3.0)
Collecting packaging<25,>=23.0 (from sagemaker<3)
  Downloading packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: pandas>=2.3.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker<3) (2.3.3)
Collecting pathos (from sagemaker<3)
  Downloading pathos-0.3.5-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: platformdirs in /opt/conda/lib/python3.12/site-packages (from sagemaker<3) (4.9.6)
Requirement already satisfied: protobuf<7.0,>=3.12 in /opt/conda/lib/python3.12/site-packages (from sagemaker<3) (6.31.1)
Requirement already satisfied: psutil in /opt/conda/lib/python3.12/site-packages (from sagemaker<3) (5.9.8)
Requirement already satisfied: pyyaml>=6.0.1 in /opt/conda/lib/python3.12/site-packages (from sagemaker<3) (6.0.3)
Requirement already satisfied: requests in /opt/conda/lib/python3.12/site-packages (from sagemaker<3) (2.34.2)
Collecting sagemaker-core<2.0.0,>=1.0.71 (from sagemaker<3)
  Downloading sagemaker_core-1.0.78-py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: schema in /opt/conda/lib/python3.12/site-packages (from sagemaker<3) (0.7.7)
Requirement already satisfied: smdebug-rulesconfig==1.0.1 in /opt/conda/lib/python3.12/site-packages (from sagemaker<3) (1.0.1)
Requirement already satisfied: tblib<4,>=1.7.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker<3) (3.2.2)
Requirement already satisfied: tqdm in /opt/conda/lib/python3.12/site-packages (from sagemaker<3) (4.67.3)
Requirement already satisfied: urllib3<3.0.0,>=1.26.8 in /opt/conda/lib/python3.12/site-packages (from sagemaker<3) (1.26.20)
Requirement already satisfied: uvicorn in /opt/conda/lib/python3.12/site-packages (from sagemaker<3) (0.46.0)
Requirement already satisfied: botocore<1.43.0,>=1.42.97 in /opt/conda/lib/python3.12/site-packages (from boto3<2.0,>=1.42.2->sagemaker<3) (1.42.97)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /opt/conda/lib/python3.12/site-packages (from boto3<2.0,>=1.42.2->sagemaker<3) (1.1.0)
Requirement already satisfied: s3transfer<0.17.0,>=0.16.0 in /opt/conda/lib/python3.12/site-packages (from boto3<2.0,>=1.42.2->sagemaker<3) (0.16.1)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /opt/conda/lib/python3.12/site-packages (from botocore<1.43.0,>=1.42.97->boto3<2.0,>=1.42.2->sagemaker<3) (2.9.0.post0)
Requirement already satisfied: graphql-core<3.3,>=3.1 in /opt/conda/lib/python3.12/site-packages (from graphene<4,>=3->sagemaker<3) (3.2.8)
Requirement already satisfied: graphql-relay<3.3,>=3.1 in /opt/conda/lib/python3.12/site-packages (from graphene<4,>=3->sagemaker<3) (3.2.0)
Requirement already satisfied: typing-extensions<5,>=4.7.1 in /opt/conda/lib/python3.12/site-packages (from graphene<4,>=3->sagemaker<3) (4.15.0)
Requirement already satisfied: zipp>=0.5 in /opt/conda/lib/python3.12/site-packages (from importlib-metadata<7.0,>=1.4.0->sagemaker<3) (4.1.0)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in /opt/conda/lib/python3.12/site-packages (from omegaconf<3,>=2.2->sagemaker<3) (4.9.3)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.43.0,>=1.42.97->boto3<2.0,>=1.42.2->sagemaker<3) (1.17.0)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<2.0.0,>=1.0.71->sagemaker<3) (2.13.4)
Requirement already satisfied: rich<15.0.0,>=13.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<2.0.0,>=1.0.71->sagemaker<3) (14.3.4)
Requirement already satisfied: mock<5.0,>4.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<2.0.0,>=1.0.71->sagemaker<3) (4.0.3)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /opt/conda/lib/python3.12/site-packages (from jsonschema->sagemaker<3) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /opt/conda/lib/python3.12/site-packages (from jsonschema->sagemaker<3) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in /opt/conda/lib/python3.12/site-packages (from jsonschema->sagemaker<3) (0.27.1)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/conda/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /opt/conda/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /opt/conda/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3) (0.4.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/conda/lib/python3.12/site-packages (from rich<15.0.0,>=13.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/conda/lib/python3.12/site-packages (from rich<15.0.0,>=13.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /opt/conda/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich<15.0.0,>=13.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3) (0.1.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.12/site-packages (from pandas>=2.3.0->sagemaker<3) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.12/site-packages (from pandas>=2.3.0->sagemaker<3) (2026.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.12/site-packages (from requests->sagemaker<3) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.12/site-packages (from requests->sagemaker<3) (3.15)
Requirement already satisfied: certifi>=2023.5.7 in /opt/conda/lib/python3.12/site-packages (from requests->sagemaker<3) (2026.5.20)
Requirement already satisfied: starlette>=0.46.0 in /opt/conda/lib/python3.12/site-packages (from fastapi->sagemaker<3) (1.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /opt/conda/lib/python3.12/site-packages (from fastapi->sagemaker<3) (0.0.4)
Requirement already satisfied: anyio<5,>=3.6.2 in /opt/conda/lib/python3.12/site-packages (from starlette>=0.46.0->fastapi->sagemaker<3) (4.13.0)
Collecting ppft>=1.7.8 (from pathos->sagemaker<3)
  Downloading ppft-1.7.8-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: dill>=0.4.1 in /opt/conda/lib/python3.12/site-packages (from pathos->sagemaker<3) (0.4.1)
Collecting pox>=0.3.7 (from pathos->sagemaker<3)
  Downloading pox-0.3.7-py3-none-any.whl.metadata (8.0 kB)
Requirement already satisfied: multiprocess>=0.70.19 in /opt/conda/lib/python3.12/site-packages (from pathos->sagemaker<3) (0.70.19)
Requirement already satisfied: click>=7.0 in /opt/conda/lib/python3.12/site-packages (from uvicorn->sagemaker<3) (8.2.1)
Requirement already satisfied: h11>=0.8 in /opt/conda/lib/python3.12/site-packages (from uvicorn->sagemaker<3) (0.16.0)
Downloading sagemaker-2.257.3-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 72.3 MB/s  0:00:00
Downloading attrs-25.4.0-py3-none-any.whl (67 kB)
Downloading packaging-24.2-py3-none-any.whl (65 kB)
Downloading sagemaker_core-1.0.78-py3-none-any.whl (444 kB)
Downloading pathos-0.3.5-py3-none-any.whl (82 kB)
Downloading pox-0.3.7-py3-none-any.whl (29 kB)
Downloading ppft-1.7.8-py3-none-any.whl (56 kB)
Installing collected packages: ppft, pox, packaging, attrs, pathos, sagemaker-core, sagemaker
  Attempting uninstall: packaging
    Found existing installation: packaging 25.0
    Uninstalling packaging-25.0:
      Successfully uninstalled packaging-25.0
  Attempting uninstall: attrs
    Found existing installation: attrs 26.1.0━━━━━━━━━━━━━━━━━━━━━ 3/7 [attrs]
    Uninstalling attrs-26.1.0:╺━━━━━━━━━━━━━━━━━━━━━━ 3/7 [attrs]
      Successfully uninstalled attrs-26.1.0━━━━━━━━━━━━━━━━━━━ 3/7 [attrs]
  Attempting uninstall: sagemaker-core0m━━━━━━━━━━━━━━━━━━━━━━ 3/7 [attrs]
    Found existing installation: sagemaker-core 2.14.0m━━━━━━━━━━━ 5/7 [sagemaker-core]
    Uninstalling sagemaker-core-2.14.0:1m╸━━━━━━━━━━━ 5/7 [sagemaker-core]
      Successfully uninstalled sagemaker-core-2.14.0━━━━━━━━━━ 5/7 [sagemaker-core]
  Attempting uninstall: sagemaker━━━╸━━━━━━━━━━━ 5/7 [sagemaker-core]
    Found existing installation: sagemaker 3.14.00m━━━━━━━━━━━ 5/7 [sagemaker-core]
    Uninstalling sagemaker-3.14.0:0m╸━━━━━━━━━━━ 5/7 [sagemaker-core]
      Successfully uninstalled sagemaker-3.14.0[90m━━━━━━━━━━━ 5/7 [sagemaker-core]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7/7 [sagemaker]/7 [sagemaker]]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
autogluon-multimodal 1.5.0 requires nvidia-ml-py3<8.0,>=7.352.0, which is not installed.
autogluon-timeseries 1.5.0 requires chronos-forecasting<2.4,>=2.2.2, which is not installed.
autogluon-timeseries 1.5.0 requires einops<1,>=0.7, which is not installed.
autogluon-timeseries 1.5.0 requires peft<0.18,>=0.13.0, which is not installed.
autogluon-multimodal 1.5.0 requires fsspec[http]<=2025.3, but you have fsspec 2026.3.0 which is incompatible.
sagemaker-studio-analytics-extension 0.3.0 requires sparkmagic==0.22.0, but you have sparkmagic 0.21.0 which is incompatible.
snowflake-connector-python 3.17.4 requires cffi<2.0.0,>=1.9, but you have cffi 2.0.0 which is incompatible.
sparkmagic 0.21.0 requires pandas<2.0.0,>=0.17.1, but you have pandas 2.3.3 which is incompatible.
sagemaker-train 1.14.0 requires sagemaker-core>=2.14.0, but you have sagemaker-core 1.0.78 which is incompatible.
sagemaker-serve 1.14.0 requires sagemaker-core>=2.14.0, but you have sagemaker-core 1.0.78 which is incompatible.
sagemaker-mlops 1.14.0 requires sagemaker-core>=2.14.0, but you have sagemaker-core 1.0.78 which is incompatible.
Successfully installed attrs-25.4.0 packaging-24.2 pathos-0.3.5 pox-0.3.7 ppft-1.7.8 sagemaker-2.257.3 sagemaker-core-1.0.78

In [1]:
import sagemaker
print(sagemaker.__version__)

sagemaker.config INFO - Fetched defaults config from location: /etc/xdg/sagemaker/config.yaml
sagemaker.config INFO - Not applying SDK defaults from location: /home/sagemaker-user/.config/sagemaker/config.yaml
sagemaker.config INFO - Applied value from config key = SageMaker.PythonSDK.Modules.Session.DefaultS3Bucket
sagemaker.config INFO - Applied value from config key = SageMaker.PythonSDK.Modules.Session.DefaultS3ObjectKeyPrefix
2.257.3

In [2]:
!ls

model-training.ipynb  test.csv	train.csv  val.csv

In [3]:
import os

import boto3

import pickle

import warnings

import numpy as np

import pandas as pd

import xgboost as xgb

import sklearn
from sklearn.metrics import r2_score
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics.pairwise import rbf_kernel
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import (
	OneHotEncoder,
	OrdinalEncoder,
	StandardScaler,
	MinMaxScaler,
	PowerTransformer,
	FunctionTransformer
)

from feature_engine.outliers import Winsorizer
from feature_engine.datetime import DatetimeFeatures
from feature_engine.selection import SelectBySingleFeaturePerformance
from feature_engine.encoding import (
	RareLabelEncoder,
	MeanEncoder,
	CountFrequencyEncoder
)

import sagemaker
from sagemaker.estimator import Estimator
from sagemaker.inputs import TrainingInput
from sagemaker.tuner import (
    IntegerParameter,
    ContinuousParameter,
    HyperparameterTuner
)

### 2. Display Settings

In [4]:
pd.set_option("display.max_columns", None)

In [5]:
sklearn.set_config(transform_output="pandas")

In [6]:
warnings.filterwarnings("ignore")

### 3. Read Datasets

In [7]:
train = pd.read_csv("train.csv")
train

,airline,date_of_journey,source,destination,dep_time,arrival_time,duration,total_stops,additional_info,price
0,Jet Airways,2019-03-21,Bangalore,New Delhi,08:55:00,19:10:00,615,1.0,In-flight meal not included,7832
1,Jet Airways,2019-03-27,Delhi,Cochin,17:30:00,04:25:00,655,1.0,In-flight meal not included,6540
2,GoAir,2019-03-09,Bangalore,New Delhi,11:40:00,14:35:00,175,0.0,No Info,7305
3,Air India,2019-06-12,Kolkata,Banglore,09:25:00,18:30:00,545,1.0,No Info,8366
4,Jet Airways,2019-03-12,Bangalore,New Delhi,22:55:00,07:40:00,525,1.0,In-flight meal not included,11087
...,...,...,...,...,...,...,...,...,...,...
6690,Jet Airways,2019-03-21,Delhi,Cochin,10:45:00,18:50:00,1925,2.0,No Info,11093
6691,Air India,2019-05-01,Kolkata,Banglore,09:25:00,18:30:00,545,1.0,No Info,8891
6692,Jet Airways,2019-06-01,Delhi,Cochin,14:00:00,19:00:00,300,1.0,In-flight meal not included,10262
6693,Air Asia,2019-06-24,Delhi,Cochin,07:55:00,13:25:00,330,1.0,No Info,6152
6694,Air India,2019-03-01,Bangalore,New Delhi,11:50:00,08:55:00,1265,1.0,1 Long layover,14594

In [8]:
val = pd.read_csv("val.csv")
val

,airline,date_of_journey,source,destination,dep_time,arrival_time,duration,total_stops,additional_info,price
0,Indigo,2019-06-24,Delhi,Cochin,20:25:00,01:30:00,305,1.0,No Info,5054
1,Multiple Carriers,2019-06-12,Delhi,Cochin,09:45:00,22:30:00,765,1.0,No Info,9646
2,Jet Airways,2019-03-12,Bangalore,New Delhi,22:55:00,15:15:00,980,1.0,In-flight meal not included,11087
3,Multiple Carriers,2019-06-06,Delhi,Cochin,13:00:00,21:00:00,480,1.0,No Info,13587
4,Jet Airways,2019-05-18,Delhi,Cochin,23:05:00,04:25:00,1760,2.0,No Info,16704
...,...,...,...,...,...,...,...,...,...,...
1669,Spicejet,2019-05-01,Chennai,Kolkata,09:45:00,12:00:00,135,0.0,No Info,3597
1670,Indigo,2019-05-01,Kolkata,Banglore,08:10:00,13:00:00,290,1.0,No Info,5069
1671,Jet Airways,2019-05-27,Delhi,Cochin,05:30:00,12:35:00,425,2.0,In-flight meal not included,15544
1672,Jet Airways,2019-06-12,Mumbai,Hyderabad,19:35:00,21:05:00,90,0.0,In-flight meal not included,3210
1673,Jet Airways,2019-06-12,Delhi,Cochin,14:00:00,19:00:00,300,1.0,No Info,14714

In [9]:
test = pd.read_csv("test.csv")
test

,airline,date_of_journey,source,destination,dep_time,arrival_time,duration,total_stops,additional_info,price
0,Jet Airways,2019-03-06,Bangalore,New Delhi,08:00:00,08:15:00,1455,1.0,No Info,17996
1,Spicejet,2019-06-06,Kolkata,Banglore,22:20:00,00:40:00,140,0.0,No Info,3873
2,Indigo,2019-03-18,Kolkata,Banglore,05:30:00,08:20:00,170,0.0,No Info,4462
3,Indigo,2019-06-27,Chennai,Kolkata,19:35:00,21:55:00,140,0.0,No Info,3597
4,Indigo,2019-05-06,Kolkata,Banglore,15:15:00,17:45:00,150,0.0,No Info,4804
...,...,...,...,...,...,...,...,...,...,...
2088,Jet Airways,2019-05-27,Delhi,Cochin,19:15:00,12:35:00,1040,1.0,In-flight meal not included,12898
2089,Multiple Carriers,2019-06-27,Delhi,Cochin,11:25:00,19:15:00,470,1.0,No Info,7155
2090,Jet Airways,2019-06-03,Delhi,Cochin,02:15:00,04:25:00,1570,1.0,In-flight meal not included,11627
2091,Multiple Carriers,2019-06-06,Delhi,Cochin,15:15:00,01:30:00,615,1.0,No Info,6795
2092,Multiple Carriers,2019-06-03,Delhi,Cochin,18:15:00,01:30:00,435,1.0,No Info,13377

### 4. Preprocessing Operations

In [10]:
# airline
air_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("grouper", RareLabelEncoder(tol=0.1, replace_with="Other", n_categories=2)),
    ("encoder", OneHotEncoder(sparse_output=False, handle_unknown="ignore"))
])

#doj
feature_to_extract = ["month", "week", "day_of_week", "day_of_year"]

doj_transformer = Pipeline(steps=[
    ("dt", DatetimeFeatures(features_to_extract=feature_to_extract, yearfirst=True, format="mixed")),
    ("scaler", MinMaxScaler())
])

# source & destination
location_pipe1 = Pipeline(steps=[
    ("grouper", RareLabelEncoder(tol=0.1, replace_with="Other", n_categories=2)),
    ("encoder", MeanEncoder()),
    ("scaler", PowerTransformer())
])

def is_north(X):
    columns = X.columns.to_list()
    north_cities = ["Delhi", "Kolkata", "Mumbai", "New Delhi"]
    return (
        X
        .assign(**{
            f"{col}_is_north": X.loc[:, col].isin(north_cities).astype(int)
            for col in columns
        })
        .drop(columns=columns)
    )

location_transformer = FeatureUnion(transformer_list=[
    ("part1", location_pipe1),
    ("part2", FunctionTransformer(func=is_north))
])

# dep_time & arrival_time
time_pipe1 = Pipeline(steps=[
    ("dt", DatetimeFeatures(features_to_extract=["hour", "minute"])),
    ("scaler", MinMaxScaler())
])

def part_of_day(X, morning=4, noon=12, eve=16, night=20):
    columns = X.columns.to_list()
    X_temp = X.assign(**{
        col: pd.to_datetime(X.loc[:, col]).dt.hour
        for col in columns
    })

    return (
        X_temp
        .assign(**{
            f"{col}_part_of_day": np.select(
                [X_temp.loc[:, col].between(morning, noon, inclusive="left"),
                 X_temp.loc[:, col].between(noon, eve, inclusive="left"),
                 X_temp.loc[:, col].between(eve, night, inclusive="left")],
                ["morning", "afternoon", "evening"],
                default="night"
            )
            for col in columns
        })
        .drop(columns=columns)
    )

time_pipe2 = Pipeline(steps=[
    ("part", FunctionTransformer(func=part_of_day)),
    ("encoder", CountFrequencyEncoder()),
    ("scaler", MinMaxScaler())
])

time_transformer = FeatureUnion(transformer_list=[
    ("part1", time_pipe1),
    ("part2", time_pipe2)
])

# duration
class RBFPercentileSimilarity(BaseEstimator, TransformerMixin):
    def __init__(self, variables=None, percentiles=[0.25, 0.5, 0.75], gamma=0.1):
        self.variables = variables
        self.percentiles = percentiles
        self.gamma = gamma


    def fit(self, X, y=None):
        if not self.variables:
            self.variables = X.select_dtypes(include="number").columns.to_list()

        self.reference_values_ = {
            col: (
                X
                .loc[:, col]
                .quantile(self.percentiles)
                .values
                .reshape(-1, 1)
            )
            for col in self.variables
        }

        return self


    def transform(self, X):
        objects = []
        for col in self.variables:
            columns = [f"{col}_rbf_{int(percentile * 100)}" for percentile in self.percentiles]
            obj = pd.DataFrame(
                data=rbf_kernel(X.loc[:, [col]], Y=self.reference_values_[col], gamma=self.gamma),
                columns=columns
            )
            objects.append(obj)
        return pd.concat(objects, axis=1)
    

def duration_category(X, short=180, med=400):
    return (
        X
        .assign(duration_cat=np.select([X.duration.lt(short),
                                    X.duration.between(short, med, inclusive="left")],
                                    ["short", "medium"],
                                    default="long"))
        .drop(columns="duration")
    )

def is_over(X, value=1000):
    return (
        X
        .assign(**{
            f"duration_over_{value}": X.duration.ge(value).astype(int)
        })
        .drop(columns="duration")
    )

duration_pipe1 = Pipeline(steps=[
    ("rbf", RBFPercentileSimilarity()),
    ("scaler", PowerTransformer())
])

duration_pipe2 = Pipeline(steps=[
    ("cat", FunctionTransformer(func=duration_category)),
    ("encoder", OrdinalEncoder(categories=[["short", "medium", "long"]]))
])

duration_union = FeatureUnion(transformer_list=[
    ("part1", duration_pipe1),
    ("part2", duration_pipe2),
    ("part3", FunctionTransformer(func=is_over)),
    ("part4", StandardScaler())
])

duration_transformer = Pipeline(steps=[
    ("outliers", Winsorizer(capping_method="iqr", fold=1.5)),
    ("imputer", SimpleImputer(strategy="median")),
    ("union", duration_union)
])

# total_stops
def is_direct(X):
    return X.assign(is_direct_flight=X.total_stops.eq(0).astype(int))


total_stops_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("", FunctionTransformer(func=is_direct))
])

# additional_info
info_pipe1 = Pipeline(steps=[
    ("group", RareLabelEncoder(tol=0.1, n_categories=2, replace_with="Other")),
    ("encoder", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
])

def have_info(X):
    return X.assign(additional_info=X.additional_info.ne("No Info").astype(int))

info_union = FeatureUnion(transformer_list=[
("part1", info_pipe1),
("part2", FunctionTransformer(func=have_info))
])

info_transformer = Pipeline(steps=[
("imputer", SimpleImputer(strategy="constant", fill_value="unknown")),
("union", info_union)
])

# column transformer
column_transformer = ColumnTransformer(transformers=[
("air", air_transformer, ["airline"]),
("doj", doj_transformer, ["date_of_journey"]),
("location", location_transformer, ["source", 'destination']),
("time", time_transformer, ["dep_time", "arrival_time"]),
("dur", duration_transformer, ["duration"]),
("stops", total_stops_transformer, ["total_stops"]),
("info", info_transformer, ["additional_info"])
], remainder="passthrough")

# feature selector
estimator = RandomForestRegressor(n_estimators=10, max_depth=3, random_state=42)

selector = SelectBySingleFeaturePerformance(
estimator=estimator,
scoring="r2",
threshold=0.1
) 

# preprocessor
preprocessor = Pipeline(steps=[
("ct", column_transformer),
("selector", selector)
])

In [11]:
preprocessor.fit(
    train.drop(columns="price"),
    train.price.copy()
)

Pipeline(steps=[('ct',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('air',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('grouper',
                                                                   RareLabelEncoder(n_categories=2,
                                                                                    replace_with='Other',
                                                                                    tol=0.1)),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['airline']),
                                                 ('doj',
                                                  Pipeline(steps=[('dt',
                                                                   Datetime...
                                                                                                                                     replace_with='Other',
                                                                                                                                     tol=0.1)),
                                                                                                                   ('encoder',
                                                                                                                    OneHotEncoder(handle_unknown='ignore',
                                                                                                                                  sparse_output=False))])),
                                                                                                  ('part2',
                                                                                                   FunctionTransformer(func=<function have_info at 0x7f10234a4180>))]))]),
                                                  ['additional_info'])])),
                ('selector',
                 SelectBySingleFeaturePerformance(estimator=RandomForestRegressor(max_depth=3,
                                                                                  n_estimators=10,
                                                                                  random_state=42),
                                                  scoring='r2',
                                                  threshold=0.1))])

In [12]:
preprocessor.transform(train.drop(columns="price"))

,air__airline_Indigo,air__airline_Jet Airways,air__airline_Other,doj__date_of_journey_week,doj__date_of_journey_day_of_year,location__source,location__destination,dur__duration_rbf_25,dur__duration_cat,dur__duration_over_1000,dur__duration,stops__total_stops,stops__is_direct_flight
0,0.0,1.0,0.0,0.176471,0.169492,-0.857930,-0.736484,-0.364262,2.0,0,-0.033916,1.0,0
1,0.0,1.0,0.0,0.235294,0.220339,1.065418,1.061694,-0.364262,2.0,0,0.046422,1.0,0
2,0.0,0.0,1.0,0.058824,0.067797,-0.857930,-0.736484,2.373008,0.0,0,-0.917631,0.0,1
3,0.0,0.0,0.0,0.882353,0.872881,-0.203928,-0.224351,-0.364262,2.0,0,-0.174507,1.0,0
4,0.0,1.0,0.0,0.117647,0.093220,-0.857930,-0.736484,-0.364262,2.0,0,-0.214676,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6690,0.0,1.0,0.0,0.176471,0.169492,1.065418,1.061694,-0.364262,2.0,1,2.597145,2.0,0
6691,0.0,0.0,0.0,0.529412,0.516949,-0.203928,-0.224351,-0.364262,2.0,0,-0.174507,1.0,0
6692,0.0,1.0,0.0,0.764706,0.779661,1.065418,1.061694,-0.364262,1.0,0,-0.666576,1.0,0
6693,0.0,0.0,1.0,1.000000,0.974576,1.065418,1.061694,-0.364262,1.0,0,-0.606322,1.0,0
6694,0.0,0.0,0.0,0.000000,0.000000,-0.857930,-0.736484,-0.364262,2.0,1,1.271572,1.0,0

### 4. Preprocess Data and Upload to Bucket

In [28]:
BUCKET_NAME = "sagemaker-s3-flights-bucket"
DATA_PREFIX = "data"

In [29]:
def get_file_name(name):
    return f"/tmp/{name}-pre.csv"

In [30]:
def export_data(data, name, pre):
    X = data.drop(columns="price")
    y = data.price.copy()

    X_pre = pre.transform(X)

    df = y.to_frame().join(pd.DataFrame(X_pre))

    file_name = get_file_name(name)

    df.to_csv(
        file_name,
        index=False,
        header=False
    )

    print(f"Saved: {file_name}")

In [31]:
def upload_to_bucket(name):
    file_name = get_file_name(name)

    s3_key = f"{DATA_PREFIX}/{name}/{name}.csv"

    boto3.Session().resource("s3") \
        .Bucket(BUCKET_NAME) \
        .upload_file(file_name, s3_key)

    print(f"Uploaded: s3://{BUCKET_NAME}/{s3_key}")

In [32]:
def export_and_upload_bucket(data, name, pre):
    export_data(data, name, pre)
    upload_to_bucket(name)

In [33]:
export_and_upload_bucket(train, "train", preprocessor)

Saved: /tmp/train-pre.csv
Uploaded: s3://sagemaker-s3-flights-bucket/data/train/train.csv

In [34]:
export_and_upload_bucket(val, "val", preprocessor)

Saved: /tmp/val-pre.csv
Uploaded: s3://sagemaker-s3-flights-bucket/data/val/val.csv

In [35]:
export_and_upload_bucket(test, "test", preprocessor)

Saved: /tmp/test-pre.csv
Uploaded: s3://sagemaker-s3-flights-bucket/data/test/test.csv

In [36]:
s3 = boto3.client("s3")

response = s3.list_objects_v2(
    Bucket=BUCKET_NAME,
    Prefix="data/"
)

for obj in response.get("Contents", []):
    print(obj["Key"])

data/test/test.csv
data/train/train.csv
data/val/val.csv

### 5. Model and Hyperparameter Tuning Set-up

In [37]:
session = sagemaker.Session()
region_name = session.boto_region_name

sagemaker.config INFO - Applied value from config key = SageMaker.PythonSDK.Modules.Session.DefaultS3Bucket
sagemaker.config INFO - Applied value from config key = SageMaker.PythonSDK.Modules.Session.DefaultS3ObjectKeyPrefix

In [38]:
output_path = f"s3://{BUCKET_NAME}/model/output"

In [39]:
import os
print(os.environ.get("AWS_REGION"))

ap-south-1

In [40]:
print(session.boto_region_name)

ap-south-1

### 6. Train and Tune the Model

In [60]:
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, r2_score

# preprocess data
X_train = preprocessor.transform(train.drop(columns="price"))
y_train = train.price.copy()

X_val = preprocessor.transform(val.drop(columns="price"))
y_val = val.price.copy()

X_test = preprocessor.transform(test.drop(columns="price"))
y_test = test.price.copy()

In [61]:
# train model locally
model = XGBRegressor(
    objective="reg:squarederror",
    n_estimators=200,
    learning_rate=0.1,
    max_depth=5,
    subsample=0.8,
    colsample_bytree=0.8,
    reg_alpha=0.1,
    random_state=42
)

model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.1, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=5, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=200, n_jobs=None,
             num_parallel_tree=None, random_state=42, ...)

In [62]:
# validation predictions
val_preds = model.predict(X_val)

rmse = np.sqrt(mean_squared_error(y_val, val_preds))
r2 = r2_score(y_val, val_preds)

print("Validation RMSE:", rmse)
print("Validation R²:", r2)

Validation RMSE: 2158.2006394216455
Validation R²: 0.7907838225364685

In [63]:
# test predictions
test_preds = model.predict(X_test)

test_rmse = np.sqrt(mean_squared_error(y_test, test_preds))
test_r2 = r2_score(y_test, test_preds)

print("Test RMSE:", test_rmse)
print("Test R²:", test_r2)

Test RMSE: 2217.282571076587
Test R²: 0.7565048933029175

- The final model achieved an R² score of 0.76 on the held-out test set with an RMSE of approximately ₹2,217.

In [ ]:
boto3.Session().resource("s3").Bucket(BUCKET_NAME).upload_file(
    "model-training.ipynb",
    "model/model-training.ipynb"
)